"""add source to demands

Revision ID: 32ad0e3ac0b7
Revises: 50e1191dd273
Create Date: 2026-05-24 18:18:21.830970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ad0e3ac0b7'
down_revision: Union[str, Sequence[str], None] = '50e1191dd273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demands', sa.Column('source', sa.String(length=16), server_default='demand-form', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demands', 'source')
    # ### end Alembic commands ###
