"""initial schema

Revision ID: 50e1191dd273
Revises: 
Create Date: 2026-05-24 17:01:09.282817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e1191dd273'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('cover_image', sa.String(length=512), nullable=True),
    sa.Column('mp_url', sa.String(length=512), nullable=True),
    sa.Column('is_home_show', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('link_url', sa.String(length=512), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=False),
    sa.Column('sub_district', sa.String(length=64), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('avg_price', sa.Float(), nullable=True, comment='参考均价(元/㎡)'),
    sa.Column('price_update_at', sa.DateTime(), nullable=True),
    sa.Column('build_year_start', sa.Integer(), nullable=True),
    sa.Column('build_year_end', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.String(length=32), nullable=True, comment='住宅/商业/办公等'),
    sa.Column('total_buildings', sa.Integer(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('developer', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True, comment='数据来源'),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_info_name'), 'community_info', ['name'], unique=False)
    op.create_table('crawl_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cron_expression', sa.String(length=32), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('auction_platform', sa.String(length=32), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('province_city', sa.String(length=64), nullable=False),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=False),
    sa.Column('sub_district', sa.String(length=64), nullable=True),
    sa.Column('ring_road', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('community_name', sa.String(length=128), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('property_type', sa.String(length=32), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('layout', sa.String(length=32), nullable=True),
    sa.Column('floor_info', sa.String(length=32), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), nullable=True),
    sa.Column('orientation', sa.String(length=32), nullable=True),
    sa.Column('decoration', sa.String(length=32), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('starting_price', sa.BigInteger(), nullable=False),
    sa.Column('starting_unit_price', sa.Float(), nullable=False),
    sa.Column('appraisal_price', sa.BigInteger(), nullable=False),
    sa.Column('court_discount_rate', sa.Float(), nullable=False),
    sa.Column('deposit', sa.BigInteger(), nullable=False),
    sa.Column('increment_amount', sa.BigInteger(), nullable=False),
    sa.Column('market_deal_price', sa.BigInteger(), nullable=False),
    sa.Column('market_deal_unit_price', sa.Float(), nullable=False),
    sa.Column('market_discount_rate', sa.Float(), nullable=False),
    sa.Column('listing_min_price', sa.BigInteger(), nullable=False),
    sa.Column('latest_deal_unit_price', sa.Float(), nullable=False),
    sa.Column('latest_total_price', sa.BigInteger(), nullable=False),
    sa.Column('bargain_potential', sa.BigInteger(), nullable=False),
    sa.Column('beike_latest_deal_unit_price', sa.Float(), nullable=False),
    sa.Column('beike_latest_deal_total_price', sa.BigInteger(), nullable=False),
    sa.Column('beike_latest_deal_time', sa.DateTime(), nullable=True),
    sa.Column('auction_round', sa.String(length=16), nullable=False),
    sa.Column('auction_status', sa.String(length=16), nullable=False),
    sa.Column('auction_start_time', sa.DateTime(), nullable=True),
    sa.Column('auction_end_time', sa.DateTime(), nullable=True),
    sa.Column('court_name', sa.String(length=128), nullable=True),
    sa.Column('case_number', sa.String(length=64), nullable=True),
    sa.Column('announcement_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('loan_support', sa.Boolean(), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_source_url'), 'properties', ['source_url'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('unionid', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('inviter_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_inviter_id'), 'users', ['inviter_id'], unique=False)
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_table('browse_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('history_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browse_history_user_id'), 'browse_history', ['user_id'], unique=False)
    op.create_table('crawl_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['crawl_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_records_property_id'), 'crawl_records', ['property_id'], unique=False)
    op.create_index(op.f('ix_crawl_records_task_id'), 'crawl_records', ['task_id'], unique=False)
    op.create_table('demands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=True),
    sa.Column('budget', sa.String(length=32), nullable=True),
    sa.Column('own_funds', sa.String(length=32), nullable=True),
    sa.Column('target_district', sa.String(length=64), nullable=True),
    sa.Column('agent_wechat', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demands_user_id'), 'demands', ['user_id'], unique=False)
    op.create_table('property_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('thumb_url', sa.String(length=512), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_images_property_id'), 'property_images', ['property_id'], unique=False)
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index(op.f('ix_property_images_property_id'), table_name='property_images')
    op.drop_table('property_images')
    op.drop_index(op.f('ix_demands_user_id'), table_name='demands')
    op.drop_table('demands')
    op.drop_index(op.f('ix_crawl_records_task_id'), table_name='crawl_records')
    op.drop_index(op.f('ix_crawl_records_property_id'), table_name='crawl_records')
    op.drop_table('crawl_records')
    op.drop_index(op.f('ix_browse_history_user_id'), table_name='browse_history')
    op.drop_table('browse_history')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_index(op.f('ix_users_inviter_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_properties_source_url'), table_name='properties')
    op.drop_table('properties')
    op.drop_table('crawl_tasks')
    op.drop_index(op.f('ix_community_info_name'), table_name='community_info')
    op.drop_table('community_info')
    op.drop_table('banners')
    op.drop_table('articles')
    # ### end Alembic commands ###
